package com.pismo.banking.account.internal.service;

import com.pismo.banking.account.api.AccountService;
import com.pismo.banking.account.api.dto.AccountRequest;
import com.pismo.banking.account.api.dto.AccountResponse;
import com.pismo.banking.account.internal.exception.AccountAlreadyExistsException;
import com.pismo.banking.account.internal.mapper.AccountMapper;
import com.pismo.banking.account.internal.model.Account;
import com.pismo.banking.account.internal.repository.AccountRepository;
import com.pismo.banking.common.exception.AccountNotFoundException;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

/**
 * Concrete implementation of the {@link AccountService} interface.
 * Manages the business logic and data access operations for bank accounts.
 *
 * <p>Uses Spring's {@code @Service} stereotype and manages transactions declaratively
 * via {@code @Transactional}.</p>
 */
@Service
@Transactional
public class AccountServiceImpl implements AccountService {

    private final AccountRepository accountRepository;

    public AccountServiceImpl(final AccountRepository accountRepository) {
        this.accountRepository = accountRepository;
    }

    /**
     * @inheritDoc
     * <p>This implementation ensures the document number is unique before saving the new account
     * entity generated by the {@link AccountMapper}.</p>
     */
    @Override
    public AccountResponse createAccount(final AccountRequest accountRequest) {
        final String documentNumber = accountRequest.documentNumber();
        if(accountRepository.existsByDocumentNumber(documentNumber)){
            throw new AccountAlreadyExistsException(documentNumber);
        }

        final Account account = AccountMapper.toEntity(accountRequest);
        final Account savedAccount = accountRepository.save(account);
        return AccountMapper.toDto(savedAccount);
    }

    /**
     * @inheritDoc
     * <p>Retrieves the account entity via the repository and maps it to a DTO.
     * Throws {@link AccountNotFoundException} if the ID is not found.</p>
     */
    @Override
    public AccountResponse getAccountById(final Long accountId) {
        return accountRepository.findById(accountId)
                .map(AccountMapper::toDto)
                .orElseThrow(() -> new AccountNotFoundException(accountId));
    }

    /**
     * @inheritDoc
     * <p>Performs a quick existence check using a repository count/exists method
     * and throws {@link AccountNotFoundException} if the ID is missing.</p>
     */
    @Override
    public void validateAccountExists(final Long accountId) {
        if(!accountRepository.existsById(accountId)){
            throw new AccountNotFoundException(accountId);
        }
    }

    @Override
    public Account findById(final Long accountId) {
        return accountRepository.findById(accountId)
                .orElseThrow(() -> new AccountNotFoundException(accountId));
    }

    @Override
    public void updateAccount(final Account account) {
        accountRepository.save(account);
    }
}
