package com.pismo.banking.transaction.internal.repository;

import com.pismo.banking.account.internal.model.Account;
import com.pismo.banking.account.internal.repository.AccountRepository;
import com.pismo.banking.transaction.internal.model.OperationType;
import com.pismo.banking.transaction.internal.model.Transaction;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.data.jpa.test.autoconfigure.DataJpaTest;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.List;

import static org.assertj.core.api.Assertions.assertThat;

@DataJpaTest
class TransactionRepositoryTest {

    @Autowired
    private TransactionRepository transactionRepository;

    @Autowired
    private AccountRepository accountRepository;

    @Test
    @DisplayName("Should save a transaction and map the enum and account ID correctly")
    void whenSaveTransaction_thenPersistenceWorks() {
        // Given an existing account in the database
        Account existingAccount = new Account(null, "11122233344");

        final Account savedAccount = accountRepository.save(existingAccount);
        Long accountId = savedAccount.getAccountId();

        // Given a transaction entity
        Transaction transaction = new Transaction(
                null, // ID generated by DB
                accountId,
                OperationType.PAYMENT,
                new BigDecimal("50.00"),
                LocalDateTime.now()
        );

        // When saving the transaction
        Transaction savedTransaction = transactionRepository.save(transaction);

        // Then verify persistence and retrieval
        assertThat(savedTransaction).isNotNull();
        assertThat(savedTransaction.getTransactionId()).isPositive();
        assertThat(savedTransaction.getAccountId()).isEqualTo(accountId);
        assertThat(savedTransaction.getOperationType()).isEqualTo(OperationType.PAYMENT);

        // Verify we can find it back from the repository
        List<Transaction> foundTransactions = transactionRepository.findAll();
        assertThat(foundTransactions).hasSize(1);
    }
}